config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :materials
  resources :levels
  devise_for :users
  root to: "home#index" 
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


   #Enables implicit order column for UUID
  self.implicit_order_column = "created_at"
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user
  belongs_to :level
  belongs_to :material
  #has_many :exercices
  has_rich_text :content

  #Avoid N+1 queries
  Course.all.with_rich_text_content # Preload the body without attachments.
  Course.all.with_rich_text_content_and_embeds # Preload both body and attachments.

  #PRESENTE
  validates :slug,
            :title,
            :author,
            :content,
            :level_id,
            :material_id,
             presence: true
  
  ################## VALIDATES  ###############
  validates :content, length: { minimum:100 }
  

  ################## SLUG ###############
  extend FriendlyId
    friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/models/level.rb
class Level < ApplicationRecord
  
  belongs_to :user
  has_many :courses

  validates :title,
            :user_id,
            :slug, presence: true
 
  #SLUG
  extend FriendlyId
    friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/models/material.rb
class Material < ApplicationRecord
 
  belongs_to :user
  has_many :courses

  validates :title,
            :user_id,
            :slug, presence: true

  ############ SLUG ###########
  extend FriendlyId
    friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :materials
  has_many :levels
  has_many :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_materials, only: [:index, :show, :new, :edit, :create, :update]
  before_action :find_levels, only:    [:index, :show, :new, :edit, :create, :level]
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  def index
    @courses = Course.all
  end

  # GET /courses/1
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  def create
    @course         = current_user.courses.build(course_params)
    @course.author  = current_user.full_name
    @course.memo    = current_user.memo

    if @course.save
      redirect_to @course, notice: 'Course was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /courses/1
  def update
    if @course.update(course_params)
      redirect_to @course, notice: 'Course was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /courses/1
  def destroy
    @course.destroy
    redirect_to courses_url, notice: 'Course was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    #enable material
    def find_materials
      @materials = Material.all
    end

    #enable level
    def find_levels
      @levels = Level.all
    end

    # Only allow a trusted parameter "white list" through.
    def course_params
      params.require(:course).permit(:title, :content, :level_id, :material_id, :author, :user_id, :slug)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_level, only: [:show, :edit, :update, :destroy]

  # GET /levels
  def index
    @levels = Level.all
  end

  # GET /levels/1
  def show
  end

  # GET /levels/new
  def new
    @level = Level.new
  end

  # GET /levels/1/edit
  def edit
  end

  # POST /levels
  def create
    @level = current_user.levels.build(level_params)

    if @level.save
      redirect_to @level, notice: 'Level was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /levels/1
  def update
    if @level.update(level_params)
      redirect_to @level, notice: 'Level was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /levels/1
  def destroy
    @level.destroy
    redirect_to levels_url, notice: 'Level was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def level_params
      params.require(:level).permit(:title, :slug, :user_id)
    end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  # GET /materials
  def index
    @materials = Material.all
  end

  # GET /materials/1
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials
  def create
    @material = current_user.materials.build(material_params)

    if @material.save
      redirect_to @material, notice: 'Material was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /materials/1
  def update
    if @material.update(material_params)
      redirect_to @material, notice: 'Material was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /materials/1
  def destroy
    @material.destroy
    redirect_to materials_url, notice: 'Material was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def material_params
      params.require(:material).permit(:title, :slug, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def title
     base_title = "LNCLASS"
        if @title.nil?
         base_title
        else
        " #{@title} - #{base_title}"
        end
    end
#Sign in and up anywhere on app
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/courses/_form.html.erb
<%= content_for @title="Crée un Résumé." %>

<%= form_with(model: course, local: true) do |f| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, label: 'Titre:', class: "form-control", placeholder:"Le titre du resumé ..." %>
  </div>

  <div class="field my-1">
    <%= f.rich_text_area :content, class: "form-control customized-min-height",
     placeholder: "Saissir le contenu ..." %>
     <small class="small mt-2">Professeur, vous pouvez aller à l'essentiel, pour faciliter la comprehension des élèves."</small>
  </div>

    <div class="row my-2">
      <div class="col-5  col-md-3 col-lg-3">
        <div class="input-form">
          <span class="select">
            <%= f.select :material_id,
              @materials.map { |m| [m.title, m.id] },
              placeholder:"la matiere",
               hide_label: true, class:"bg-red-200" %>

          </span>
        </div>
      </div>
      <div class="col-5 col-md-3 col-lg-3">
        <div class="input-form">
          <span class="select">
            <%= f.select :level_id,
              @levels.map { |l| [l.title, l.id] },
              placeholder:"Niveau",
               hide_label: true %>
          </span>
        </div>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit "Créer le resumé",  class: "inline-flex justify-center py-2 px-4 border border-transparent 
  shadow-sm text-sm font-medium rounded-md text-white bg-blue-600
 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2
  focus:ring-blue-500" %>
    </div>
<% end %>

app/views/courses/edit.html.erb
<%= content_for @title="Modifier le resumé" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-12 col-md-7 col-lg-7 mx-auto mt-24">
        <h2 class="text-center mb-4 font-bold text-3xl">Modifier le Resumé :</h2>
        <div class="mx-auto">
            <%= render 'form', course: @course %>
        </div>
    </div>
  </div>
</div>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Level</th>
      <th>Material</th>
      <th>Author</th>
      <th>User</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= course.content %></td>
        <td><%= course.level_id %></td>
        <td><%= course.material_id %></td>
        <td><%= course.author %></td>
        <td><%= course.user_id %></td>
        <td><%= course.slug %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<div class="container-fluid">
  <div class="row">
    <!-- navbar course-->
    <%= render "courses/shared/navbar" %>
    <div class="col-12 col-md-7 col-lg-7 mx-auto ">
    
      <h2 class="text-center mb-4 font-bold text-3xl mt-24">Nouveau resumé :</h2>
        <div class="mx-auto">
          <%= render 'form', course: @course %>
        </div>
    </div>
  </div>
</div>

app/views/courses/shared/_navbar.html.erb
<!--HEADER/!-->
<!-- no header render on the home page/!-->
<% if user_signed_in? %>
<!-- Navigation -->
    <nav class="navbar navbar-expand-sm navbar-dark bg-blue-500 fixed-top">
        <div class="container">
            <%= link_to root_path, class: "navbar-brand logo font-bold" do %>LNCLASS <% end  %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">

                    <!-- Home onglet/!-->
                    <li class="nav-item nav-item_feed active">
                        <%= link_to root_path, class: "m-links nav-link active " do %>
                            <i class="fa fa-home"></i> Acceuil
                        <% end %>
                    </li>

                     <!-- user avatar/!-->
                    <li class="nav-item nav-item_feed active">
                        <%= link_to edit_user_registration_path(@user), class: " active m-links nav-link capitalize" do %>
                            <i class="fas fa-user-circle"></i>
                            <%= current_user.full_name %>
                        <% end %>
                    </li>

                     <!-- create course by teacher/!-->
                    <li class="nav-item nav-item_feed active">
                        <%= link_to root_path, class: "m-links nav-link active  " do %>
                        <i class="fas fa-users"></i> Centre D'aide
                        <% end %>
                    </li>

                    <!-- Sign out /!-->
                    <li class="nav-item nav-item_feed active">
                        <%= link_to destroy_user_session_path, method: :delete, class: "m-links nav-link active " do %>
                            <i class="fa fa-power-off" aria-hidden="true"></i> Déconnexion
                        <% end %>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
<% end %>

app/views/courses/shared/_options.html.erb
<!-- edit option-->

<% if current_user.id == @course.user_id %>
  <div class="d-flex justify-content-end">
    <%= link_to  @course, method: :delete, data: { confirm: 'voulez-vous vraiment supprimé?' } do %>
      <i class="fas fa-trash"></i> Supprimé
    <% end %>
  <span class="mx-2">
    <%= link_to  edit_course_path(@course) do %>
      <i class="fas fa-chalkboard-teacher"></i> Editer
    <% end %>
  </span>
  </div>
   
<% end %>

<%= render 'file path' %>

app/views/courses/shared/_users_card_course.html.erb
<!-- User Card for show course-->
<div class="flex items-center">
     <img class="w-10 h-10 bg-gray-200 rounded-full mr-2">
	<div class="text-sm mt-2">
		<p class="font-bold text-black leading-none capitalize -mt-2"> 
			<%= @course.author %>
	    </p>
		<p class="text-grey-dark -mt-1">
			Prof - <%= @course.material.title %>
		</p>
	</div>
</div>

app/views/courses/show.html.erb
<% content_for @title = @course.title %>

<div class="container-sm">
  <div class="row pt-16 ">
    <div class="col-12 col-md-6 col-lg-6">

      <!-- card course-->
      <h1 class="my-2 font-semibold">Résumé</h1>
      <div class="card">
        <!-- title!-->
        <h1 class="text-xl leading-tight font-bold mt-2 mx-2">
          <%= @course.title %>
        </h1>

         <!-- avatar data/!-->
        <div class="flex items-cente mt-4 ml-6">
         
          <!-- Course meta data-->
          <%= render "courses/shared/user_card_course" %>
        </div>

        <!--content/!-->
        <div class="m-2">
          <p class="mx-2" id="read_more">
            <%= @course.content.to_s.html_safe %>
          </p>
          <hr>
          <!-- Options-->
          <%= render "courses/shared/options" %>
        </div>
      </div>
    </div>
    <!-- Exercices-->
    <div class="col-12 col-md-6 col-lg-6">
      <h1 class="my-2 font-semibold">Exercices</h1>
      
      <!-- exercice card -->
      <%= render "exercice_card" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title><%= title %></title>
    <%= render "layouts/shared/headers" %>
  </head>

  <body>
    <%= render "shared/nav/navbar" %>
    <%= render "layouts/shared/noticed" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_headers.html.erb
 <!-- META DATA -->
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- META TAGS-->
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<!-- TAILWIND CSS TAGS-->
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    
<!-- FLAVICON -->

app/views/layouts/shared/_noticed.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
        <div class="flex">
            <ul>
                <%= value %>
            </ul>
            <a href="#" data-dismiss="alert" class="close">x</a>
        </div>
    </div>
<% end %>

app/views/levels/_form.html.erb
<%= form_with(model: level, local: true) do |form| %>
  <% if level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(level.errors.count, "error") %> prohibited this level from being saved:</h2>

      <ul>
        <% level.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field my-2">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions mt-2">
    <%= form.submit "Add new Level", class:'inline-flex justify-center py-2 px-4 border border-transparent 
  shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600
 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2
  focus:ring-indigo-500' %>
  </div>
<% end %>

app/views/levels/edit.html.erb
<h1>Editing Level</h1>

<%= render 'form', level: @level %>

<%= link_to 'Show', @level %> |
<%= link_to 'Back', levels_path %>

app/views/levels/index.html.erb
<div class="container"> 
<p id="notice"><%= notice %></p>

<h1>Levels</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @levels.each do |level| %>
      <tr>
        <td><%= level.title %></td>
        <td><%= level.slug %></td>
        <td><%= level.user_id %></td>
        <td><%= link_to 'Show', level %></td>
        <td><%= link_to 'Edit', edit_level_path(level) %></td>
        <td><%= link_to 'Destroy', level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Level', new_level_path,
 class:"inline-flex justify-center py-2 px-4 border border-transparent 
  shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600
 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2
  focus:ring-indigo-500" %>

</div>

app/views/levels/new.html.erb
<div class="h-screen w-full flex overflow-hidden select-none">

<%= link_to 'Back', levels_path %>
<main class="my-1 pt-2 pb-2 px-10 flex-1 bg-gray-200 dark:bg-black rounded-l-lg
		transition duration-500 ease-in-out overflow-y-auto">
 <br><h1>New Level</h1>
 

<%= render 'form', level: @level %>
</main>
</div>

app/views/levels/show.html.erb
<div class="h-screen w-full flex overflow-hidden select-none">


<main class="my-1 pt-2 pb-2 px-10 flex-1 bg-gray-200 dark:bg-black rounded-l-lg
		transition duration-500 ease-in-out overflow-y-auto">
<br>
 <br>
 <br>
 <br><p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @level.title %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @level.slug %>
</p>

<p>
  <strong>User:</strong>
  <%= @level.user_id %>
</p>

<%= link_to 'Edit', edit_level_path(@level), class:"bg-red-200" %> |
<%= link_to 'Back', levels_path,  class:"bg-purple-200"%> | <%= link_to 'New', new_level_path,  class:"bg-blue-200"%> 
</main>
</div>

app/views/materials/_form.html.erb
<%= form_with(model: material, local: true) do |form| %>
  <% if material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
        <% material.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field my-2">
    <%= form.text_field :title, placeholder:"Title matiere" %>
  </div>


  <div class="actions">
    <%= form.submit "Créer la matiere", class:"inline-flex justify-center py-2 px-4 border border-transparent 
  shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600
 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2
  focus:ring-indigo-500"%>
  </div>
<% end %>

app/views/materials/edit.html.erb
<h1>Editing Material</h1>

<%= render 'form', material: @material %>

<%= link_to 'Show', @material %> |
<%= link_to 'Back', materials_path %>

app/views/materials/index.html.erb
<div class="container">
<div class="h-screen w-full flex overflow-hidden select-none">


<main class="my-1 pt-2 pb-2 px-10 flex-1 bg-gray-200 dark:bg-black rounded-l-lg
		transition duration-500 ease-in-out overflow-y-auto">

  <p id="notice"><%= notice %></p>

<h1>Levels</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.title %></td>
        <td><%= material.slug %></td>
        <td><%= material.user_id %></td>
        <td><%= link_to 'Show', material %></td>
        <td><%= link_to 'Edit', edit_material_path(material) %></td>
        <td><%= link_to 'Destroy', material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Material', new_material_path, class:"font-bold inline-flex justify-center py-2 px-4 border border-transparent 
  shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600
 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2
  focus:ring-indigo-500" %>
</main>
</div>
</div>

app/views/materials/new.html.erb
<div class="h-screen w-full flex overflow-hidden select-none mt-16"> 
  <main class="my-1 pt-2 pb-2 px-10 flex-1 bg-gray-200 dark:bg-black rounded-l-lg
        transition duration-500 ease-in-out overflow-y-auto">
    <h1>New Material</h1>

    <%= render 'form', material: @material %>
    <%= link_to 'Back', materials_path %>
  </main>
</div>

app/views/materials/show.html.erb
<% content_for @title="kara" %>

<div class="container-fluid md:mt-12">
<!-- material title/!-->
  <div class="container">
    <h1 class="text-center font-semibold">
      Special <%= @material.title %>
    </h1>
  </div>
  <hr />
    
</div>

app/views/shared/nav/_navbar.html.erb
<!--HEADER/!-->
<!-- no header render on the home page/!-->
<% if user_signed_in? %>
<!-- Navigation -->
    <nav class="navbar navbar-expand-sm navbar-dark bg-blue-500 fixed-top">
        <div class="container">
            <%= link_to root_path, class: "navbar-brand logo font-bold" do %>LNCLASS <% end  %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <!-- Home onglet/!-->
                    <li class="nav-item nav-item_feed active">
                        <%= link_to root_path, class: "m-links nav-link active " do %>
                            <i class="fa fa-home"></i> Acceuil
                        <% end %>
                    </li>

                     <!-- user avatar/!-->
                    <li class="nav-item nav-item_feed active">
                        <%= link_to edit_user_registration_path(@user), class: " active m-links nav-link capitalize" do %>
                            <i class="fas fa-user-circle"></i>
                            <%= current_user.full_name %>
                        <% end %>
                    </li>
                     <!-- create course by teacher/!-->
                    
                    <% if current_user.role == "teacher" %>
                        <li class="nav-item nav-item_feed active">
                            <%= link_to dashboard_index_path, class: "m-links nav-link active  " do %>
                            <i class="fas fa-users"></i> TablesClass
                            <% end %>
                        </li>
                    <% elsif current_user.role == "team" %>
                    <li class="nav-item nav-item_feed active">
                            <%= link_to dashboard_index_path, class: "m-links nav-link active  " do %>
                            <i class="fas fa-users"></i> Admistration
                            <% end %>
                        </li>
                    <% end %>
                    

                    <!-- Sign out /!-->
                    <li class="nav-item nav-item_feed active">
                        <%= link_to destroy_user_session_path, method: :delete, class: "m-links nav-link active " do %>
                            <i class="fa fa-power-off" aria-hidden="true"></i> Déconnexion
                        <% end %>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
<% end %>